### ISSUE TITLE
[Bug] Upload images when saving a new app crashes

### ISSUE THREAD

**Issue by aniri** [code4romania/civichq-api#101]
When trying to add a new app, a 500 server error is received when uploading the new logo. 

![Capture](https://user-images.githubusercontent.com/1358055/59679815-801f2900-91d8-11e9-9750-b785db48738e.JPG)

**Comment by RaduCStefanescu** [comment]
This was a configuration issue on the S3 bucket details.
Redeployed with correct details, it is working now.
