### ISSUE TITLE
Diacriticile nu sunt salvate corect in baza de date

### ISSUE THREAD

**Issue by Puiu** [code4romania/civichq-api#49]
In API ajung corect, dar se pierd in baza de date.
![screen shot 2016-10-18 at 9 46 46 pm](https://cloud.githubusercontent.com/assets/4242822/19494087/b89ade1e-957d-11e6-8b31-95df4aa0b11b.png)
![screen shot 2016-10-18 at 9 48 30 pm](https://cloud.githubusercontent.com/assets/4242822/19494086/b8975b22-957d-11e6-8866-c5d4f5f27fdc.png)

**Comment by ArthurianX** [comment]
Deci e o mizerie undeva mare la mijloc.

Am debuguit toata partea de node cu wireshark, desi console.log-ul da bine, m-am uitat sa vad si ce se trimite (https://www.dropbox.com/s/i9r6uvz017kfljd/Screenshot%202016-10-24%2023.56.58.png?dl=0) si se trimit caracterele latine encodate aparent calumea.

M-am conectat si la mysql pe aws, nu am avut access sa enable logging in tabel, dar toate tabele par sa aiba charset-ul si collation ul ok.

Din capitolul educated guesses, cred ca mai e ceva peste acel mysql la amazon, cine are acces acolo sa va uitati va rog, daca reusesc sa enable log in aws la queryes si vedem ca merge call-ul cu diacriticele encodate doar ceva serviciu aws poate fi de vina.

@Puiu ^

**Comment by ArthurianX** [comment]
Check this out: http://www.somacon.com/p580.php - Pe AWS-ul la care ne conectam noi sunt facute chestiile astea ?

**Comment by Puiu** [comment]
API-ul foloseste sequalize la apelarea procedurii stocate. Ma gandesc ca ar putea fi de aici? Am pus o optiune in config pt utf8 si lq sequalize, dar tot nu a mers...

**Comment by ArthurianX** [comment]
M-am jucat si eu cu optiunile alea: `utf8_general_ci`, `utf8_unicode_ci`, am inspectat cu wireshark cum comunica serverul de node cu mysql server de pe amazon si pare ok, imi pare a fi o buba la aws, ceva layer de configurare / filtrare peste db-ul de acolo, fiindca si in db-ul de acolo proprietatile tabelelor sunt bune. Nu sunt 100% sigur inca, dar diseara dau resume la debugging.

**Comment by ArthurianX** [comment]
Mi a facut @razvanpavel un cont pe aws sa am control  asupra a tot ce se intampla acolo si mi-am tras o baza de date.
Am nevoie de un dump de la baza de date actuala, sau un seed sa imi creez toate tabelele si field-urile.
