### ISSUE TITLE
Add archiving functionality for apps

### ISSUE THREAD

**Issue by aniri** [code4romania/civichq-api#74]
Add soft delete functionality

- add archived flag column in db for apps
- add a delete call for apps that will mark an app as archived in db
- only admins have access to this call

Update get apps call for admin

- apps marked as archived should not be displayed for admin

Best practices

- codebase language should be English
- we :two_hearts: unit tests

related to  #https://github.com/code4romania/civichq-client/issues/51

**Comment by czmole** [comment]
I could pick this one also.

**Comment by aniri** [comment]
@czmole that would be great! thanks!
