### ISSUE TITLE
Handle new technologies field for apps

### ISSUE THREAD

**Issue by aniri** [code4romania/civichq-api#81]
A new field should be added for apps:
- update scripts for apps table and add a new column for storing a list of technologies as strings
- update add and edit app calls - update the info to be saved in db when filling in the add app form to include the list of technologies
- update the response returned by all calls for retrieving the apps list or info about an app; add the info from the technologies field

Best practices

* codebase language should be English
* we :two_hearts: unit tests

**Comment by paul-ghiran** [comment]
Need to rebase on #78

**Comment by paul-ghiran** [comment]
- [ ] update scripts for apps table and add a new column for storing a list of technologies as strings
- [ ] update add and edit app calls - update the info to be saved in db when filling in the add app form to include the list of technologies
- [ ] update the response returned by all calls for retrieving the apps list or info about an app; add the info from the technologies field
