### ISSUE TITLE
Update editapp call to update also the isActive field for apps

### ISSUE THREAD

**Issue by aniri** [code4romania/civichq-api#91]
The isActive field is a new field that was recently added for apps. The editApp call should be enhanced to permit editing this field.

- update edit app procedure to include the new field
- update edit app call - update the info to be saved in db

Best practices

* codebase language should be English
* we :two_hearts: unit tests

**Comment by czmole** [comment]
May I pick this one? 😊

**Comment by aniri** [comment]
> May I pick this one?

sure :smile:

**Comment by aniri** [comment]
@czmole this one is also very similar https://github.com/code4romania/civichq-api/issues/94 . if you want to handle both it would be awesome!

**Comment by czmole** [comment]
OK, I will try to see both of them.

Thank you!
